<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MusicianProfile extends Model
{
    use HasFactory;

    // ── Valid verification states ────────────────────────────────────────────
    const STATUS_UNVERIFIED = 'unverified';
    const STATUS_PENDING    = 'pending';
    const STATUS_APPROVED   = 'approved';
    const STATUS_REJECTED   = 'rejected';

    /**
     * Auto-sync the legacy `is_verified` boolean whenever
     * `verification_status` is changed, so we never have to update
     * both fields manually in controllers.
     */
    protected static function booted(): void
    {
        static::saving(function (MusicianProfile $profile) {
            // Sync is_verified boolean when verification_status changes
            if ($profile->isDirty('verification_status')) {
                $profile->is_verified = $profile->verification_status === self::STATUS_APPROVED;
            }

            // Auto-generate a unique slug from stage_name if not set or stage_name changed
            if (empty($profile->slug) || $profile->isDirty('stage_name')) {
                $baseSlug = Str::slug($profile->stage_name, '-');
                $slug     = $baseSlug;
                $counter  = 1;

                // Ensure uniqueness by appending a counter suffix when needed
                while (
                    static::where('slug', $slug)
                          ->when($profile->exists, fn($q) => $q->where('id', '!=', $profile->id))
                          ->exists()
                ) {
                    $slug = $baseSlug . '-' . $counter++;
                }

                $profile->slug = $slug;
            }
        });
    }

    // ── Query Scopes ─────────────────────────────────────────────────────────
    public function scopePending($query)    { return $query->where('verification_status', self::STATUS_PENDING); }
    public function scopeApproved($query)   { return $query->where('verification_status', self::STATUS_APPROVED); }
    public function scopeRejected($query)   { return $query->where('verification_status', self::STATUS_REJECTED); }
    public function scopeUnverified($query) { return $query->where('verification_status', self::STATUS_UNVERIFIED); }
    public function scopeByStatus($query, string $status) { return $query->where('verification_status', $status); }

    protected $fillable = [
        'user_id',
        'stage_name',
        'slug',
        'bio',
        'location',
        'hourly_rate',
        'profile_picture',
        'is_verified',
        'phone',
        'instagram',
        'facebook',
        'youtube',
        'tiktok',
        'spotify',
        'coverage_notes',
        'verification_status',
        'id_document_path',
        'rejection_reason',
        'verified_at',
        'verified_by',
    ];

    /**
     * Fields that are generated by the database engine; they are read-only
     * from Eloquent's perspective and must NOT be included in INSERT/UPDATE.
     */
    protected $generated = ['presupuesto_con_impuesto'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function genres()
    {
        return $this->belongsToMany(Genre::class , 'genre_musician_profile');
    }

    public function hiringRequests()
    {
        return $this->hasMany(HiringRequest::class);
    }

    public function promotions()
    {
        return $this->hasMany(Promotion::class);
    }

    public function castingApplications()
    {
        return $this->hasMany(CastingApplication::class , 'musician_profile_id');
    }

    public function media()
    {
        return $this->hasMany(MusicianMedia::class);
    }

    public function profilePictureUrl()
    {
        if (!$this->profile_picture) {
            return asset('images/default-avatar.png'); // Si tienes un avatar por defecto
        }

        if (filter_var($this->profile_picture, FILTER_VALIDATE_URL)) {
            return $this->profile_picture;
        }

        // Force to use our custom file streaming route, bypassing EasyPanel symlink issues
        return url('file/' . $this->profile_picture);
    }

    public function calendarEvents()
    {
        return $this->hasMany(MusicianCalendarEvent::class);
    }

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }

    public function averageRating()
    {
        return $this->reviews()->avg('rating') ?? 0;
    }

    public function verifiedBy()
    {
        return $this->belongsTo(User::class, 'verified_by');
    }

    public function groupTypes()
    {
        return $this->belongsToMany(GroupType::class);
    }

    public function eventTypes()
    {
        return $this->belongsToMany(EventType::class);
    }
}
